slack_settings:
  token: 'YOUR_SLACK_TOKEN'
zilack_settings:
  webhooks_enabled: 1
  webhooks_listener_host: 0.0.0.0
  webhooks_listener_port: 8081

  identities:
    primary:
      name: 'Primary Identity'
      icon: 'robot_face'
    burger:
      name: 'Burger Identity'
      icon: 'hamburger'